// <auto-generated />
using System;
using Ksu.Cs.Portal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KSU.CS.Portal.Migrations
{
    [DbContext(typeof(PortalContext))]
    [Migration("20220228172745_MoveAccessibleToNodes")]
    partial class MoveAccessibleToNodes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Ksu.Cs.Portal.Areas.Maps.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BuildingAbrev")
                        .HasColumnType("TEXT");

                    b.Property<string>("BuildingName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("X")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Building");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildingAbrev = "A",
                            BuildingName = "Anderson Hall",
                            CreatedOn = new DateTime(2022, 2, 28, 11, 27, 44, 668, DateTimeKind.Local).AddTicks(8941),
                            UpdatedOn = new DateTime(2022, 2, 28, 11, 27, 44, 671, DateTimeKind.Local).AddTicks(1012),
                            X = 100ul,
                            Y = 300ul
                        });
                });

            modelBuilder.Entity("Ksu.Cs.Portal.Areas.Maps.Models.DoorHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("CloseTime")
                        .HasColumnType("TEXT");

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DoorId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("OpenTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DoorId");

                    b.ToTable("DoorHours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CloseTime = new TimeSpan(0, 17, 15, 0, 0),
                            DayOfWeek = (byte)0,
                            DoorId = 3,
                            OpenTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            CloseTime = new TimeSpan(0, 17, 15, 0, 0),
                            DayOfWeek = (byte)1,
                            DoorId = 3,
                            OpenTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            CloseTime = new TimeSpan(0, 17, 15, 0, 0),
                            DayOfWeek = (byte)2,
                            DoorId = 3,
                            OpenTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            CloseTime = new TimeSpan(0, 17, 15, 0, 0),
                            DayOfWeek = (byte)3,
                            DoorId = 3,
                            OpenTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            CloseTime = new TimeSpan(0, 17, 15, 0, 0),
                            DayOfWeek = (byte)4,
                            DoorId = 3,
                            OpenTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            CloseTime = new TimeSpan(0, 17, 15, 0, 0),
                            DayOfWeek = (byte)5,
                            DoorId = 3,
                            OpenTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            CloseTime = new TimeSpan(0, 17, 15, 0, 0),
                            DayOfWeek = (byte)6,
                            DoorId = 3,
                            OpenTime = new TimeSpan(0, 8, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("Ksu.Cs.Portal.Areas.Maps.Models.Edge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DestinationNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartNodeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("DestinationNodeId");

                    b.HasIndex("StartNodeId");

                    b.ToTable("Edge");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildingId = 1,
                            DestinationNodeId = 3,
                            StartNodeId = 1
                        },
                        new
                        {
                            Id = 2,
                            BuildingId = 1,
                            DestinationNodeId = 2,
                            StartNodeId = 3
                        },
                        new
                        {
                            Id = 3,
                            BuildingId = 1,
                            DestinationNodeId = 1,
                            StartNodeId = 3
                        },
                        new
                        {
                            Id = 4,
                            BuildingId = 1,
                            DestinationNodeId = 3,
                            StartNodeId = 2
                        });
                });

            modelBuilder.Entity("Ksu.Cs.Portal.Areas.Maps.Models.Floor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildingId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("FloorLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("FloorMap")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Floor");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            BuildingId = 1,
                            CreatedOn = new DateTime(2022, 2, 28, 11, 27, 44, 671, DateTimeKind.Local).AddTicks(8025),
                            FloorLevel = "Third",
                            FloorMap = "null",
                            UpdatedOn = new DateTime(2022, 2, 28, 11, 27, 44, 671, DateTimeKind.Local).AddTicks(8275)
                        },
                        new
                        {
                            Id = 3,
                            BuildingId = 1,
                            CreatedOn = new DateTime(2022, 2, 28, 11, 27, 44, 671, DateTimeKind.Local).AddTicks(8474),
                            FloorLevel = "Second",
                            FloorMap = "null",
                            UpdatedOn = new DateTime(2022, 2, 28, 11, 27, 44, 671, DateTimeKind.Local).AddTicks(8481)
                        },
                        new
                        {
                            Id = 2,
                            BuildingId = 1,
                            CreatedOn = new DateTime(2022, 2, 28, 11, 27, 44, 671, DateTimeKind.Local).AddTicks(8484),
                            FloorLevel = "First",
                            FloorMap = "null",
                            UpdatedOn = new DateTime(2022, 2, 28, 11, 27, 44, 671, DateTimeKind.Local).AddTicks(8486)
                        },
                        new
                        {
                            Id = 1,
                            BuildingId = 1,
                            CreatedOn = new DateTime(2022, 2, 28, 11, 27, 44, 671, DateTimeKind.Local).AddTicks(8489),
                            FloorLevel = "Basement",
                            FloorMap = "null",
                            UpdatedOn = new DateTime(2022, 2, 28, 11, 27, 44, 671, DateTimeKind.Local).AddTicks(8491)
                        });
                });

            modelBuilder.Entity("Ksu.Cs.Portal.Areas.Maps.Models.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Accessible")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildingId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("X")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Node");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Accessible = false,
                            BuildingId = 1,
                            CreatedOn = new DateTime(2022, 2, 28, 11, 27, 44, 671, DateTimeKind.Local).AddTicks(8649),
                            UpdatedOn = new DateTime(2022, 2, 28, 11, 27, 44, 671, DateTimeKind.Local).AddTicks(8653),
                            X = 600ul,
                            Y = 600ul
                        });
                });

            modelBuilder.Entity("Ksu.Cs.Portal.Areas.Maps.Models.RoomTag", b =>
                {
                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoomId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("RoomTag");
                });

            modelBuilder.Entity("Ksu.Cs.Portal.Areas.Maps.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("Ksu.Cs.Portal.Models.PortalUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Eid")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFaculty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStaff")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStudent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTeachingAssistant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Roles")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Eid")
                        .IsUnique();

                    b.ToTable("PortalUser");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Eid = "nhbean",
                            FirstName = "Nathan",
                            IsAdmin = true,
                            IsFaculty = true,
                            IsStaff = false,
                            IsStudent = false,
                            IsTeachingAssistant = false,
                            LastName = "Bean",
                            Roles = 160
                        },
                        new
                        {
                            Id = 2,
                            Eid = "russfeld",
                            FirstName = "Russ",
                            IsAdmin = true,
                            IsFaculty = true,
                            IsStaff = false,
                            IsStudent = false,
                            IsTeachingAssistant = false,
                            LastName = "Feldhausen",
                            Roles = 160
                        },
                        new
                        {
                            Id = 3,
                            Eid = "weeser",
                            FirstName = "Josh",
                            IsAdmin = true,
                            IsFaculty = true,
                            IsStaff = false,
                            IsStudent = false,
                            IsTeachingAssistant = false,
                            LastName = "Weese",
                            Roles = 160
                        });
                });

            modelBuilder.Entity("Ksu.Cs.Portal.Areas.Maps.Models.Door", b =>
                {
                    b.HasBaseType("Ksu.Cs.Portal.Areas.Maps.Models.Node");

                    b.ToTable("Door");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Accessible = false,
                            BuildingId = 1,
                            CreatedOn = new DateTime(2022, 2, 28, 11, 27, 44, 671, DateTimeKind.Local).AddTicks(3361),
                            UpdatedOn = new DateTime(2022, 2, 28, 11, 27, 44, 671, DateTimeKind.Local).AddTicks(3604),
                            X = 400ul,
                            Y = 500ul
                        });
                });

            modelBuilder.Entity("Ksu.Cs.Portal.Areas.Maps.Models.Room", b =>
                {
                    b.HasBaseType("Ksu.Cs.Portal.Areas.Maps.Models.Node");

                    b.Property<int>("FloorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomNumber")
                        .HasColumnType("TEXT");

                    b.HasIndex("FloorId");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Accessible = false,
                            BuildingId = 1,
                            CreatedOn = new DateTime(2022, 2, 28, 11, 27, 44, 671, DateTimeKind.Local).AddTicks(9566),
                            UpdatedOn = new DateTime(2022, 2, 28, 11, 27, 44, 671, DateTimeKind.Local).AddTicks(9577),
                            X = 500ul,
                            Y = 400ul,
                            FloorId = 4,
                            RoomNumber = "A308"
                        });
                });

            modelBuilder.Entity("Ksu.Cs.Portal.Areas.Maps.Models.DoorHours", b =>
                {
                    b.HasOne("Ksu.Cs.Portal.Areas.Maps.Models.Door", "Door")
                        .WithMany("DoorHours")
                        .HasForeignKey("DoorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Door");
                });

            modelBuilder.Entity("Ksu.Cs.Portal.Areas.Maps.Models.Edge", b =>
                {
                    b.HasOne("Ksu.Cs.Portal.Areas.Maps.Models.Building", "Building")
                        .WithMany("Edges")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ksu.Cs.Portal.Areas.Maps.Models.Node", "DestinationNode")
                        .WithMany("ToEdges")
                        .HasForeignKey("DestinationNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ksu.Cs.Portal.Areas.Maps.Models.Node", "StartNode")
                        .WithMany("FromEdges")
                        .HasForeignKey("StartNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("DestinationNode");

                    b.Navigation("StartNode");
                });

            modelBuilder.Entity("Ksu.Cs.Portal.Areas.Maps.Models.Floor", b =>
                {
                    b.HasOne("Ksu.Cs.Portal.Areas.Maps.Models.Building", "Building")
                        .WithMany("Floors")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("Ksu.Cs.Portal.Areas.Maps.Models.Node", b =>
                {
                    b.HasOne("Ksu.Cs.Portal.Areas.Maps.Models.Building", "Building")
                        .WithMany("Nodes")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("Ksu.Cs.Portal.Areas.Maps.Models.RoomTag", b =>
                {
                    b.HasOne("Ksu.Cs.Portal.Areas.Maps.Models.Room", "Room")
                        .WithMany("RoomTags")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ksu.Cs.Portal.Areas.Maps.Models.Tag", "Tag")
                        .WithMany("RoomTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Ksu.Cs.Portal.Areas.Maps.Models.Door", b =>
                {
                    b.HasOne("Ksu.Cs.Portal.Areas.Maps.Models.Node", null)
                        .WithOne()
                        .HasForeignKey("Ksu.Cs.Portal.Areas.Maps.Models.Door", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ksu.Cs.Portal.Areas.Maps.Models.Room", b =>
                {
                    b.HasOne("Ksu.Cs.Portal.Areas.Maps.Models.Floor", "Floor")
                        .WithMany("Rooms")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ksu.Cs.Portal.Areas.Maps.Models.Node", null)
                        .WithOne()
                        .HasForeignKey("Ksu.Cs.Portal.Areas.Maps.Models.Room", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("Ksu.Cs.Portal.Areas.Maps.Models.Building", b =>
                {
                    b.Navigation("Edges");

                    b.Navigation("Floors");

                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("Ksu.Cs.Portal.Areas.Maps.Models.Floor", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Ksu.Cs.Portal.Areas.Maps.Models.Node", b =>
                {
                    b.Navigation("FromEdges");

                    b.Navigation("ToEdges");
                });

            modelBuilder.Entity("Ksu.Cs.Portal.Areas.Maps.Models.Tag", b =>
                {
                    b.Navigation("RoomTags");
                });

            modelBuilder.Entity("Ksu.Cs.Portal.Areas.Maps.Models.Door", b =>
                {
                    b.Navigation("DoorHours");
                });

            modelBuilder.Entity("Ksu.Cs.Portal.Areas.Maps.Models.Room", b =>
                {
                    b.Navigation("RoomTags");
                });
#pragma warning restore 612, 618
        }
    }
}
